### ISSUE TITLE
DeviceApps.openApp() fails when called from a background channel

### ISSUE THREAD

**Issue by michael-ottink** [g123k/flutter_plugin_device_apps#45]
***Introduction**

I am running flutter v1.17.5 DeviceApps v1.0.10 and SystemAlertWindow v0.2.2+3 (intentially not the latest version). And I want to open my app from a system alert window that is running in the foreground, even when the app is closed.

I am using the **SystemOverlayWindow** plugin and the plugin is a activity [SystemAlertWindowPlugin.java][1]

In my **Application.kt** I register the plugins and pass the registry

    public class Application: FlutterApplication(), PluginRegistrantCallback {
    
       override fun onCreate() {
         super.onCreate();
         FlutterFirebaseMessagingService.setPluginRegistrant(this);
         SystemAlertWindowPlugin.setPluginRegistrant(this);
         createNotificationChannels();
         FlutterMain.startInitialization(this);
       }
    
       override fun registerWith(registry: PluginRegistry?) {
        if (!registry!!.hasPlugin("io.flutter.plugins.firebasemessaging")) {
          FirebaseMessagingPlugin.registerWith(registry!!.registrarFor("io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin"));
        }
        if (!registry!!.hasPlugin("in.jvapps.system_alert_window")) {
          SystemAlertWindowPlugin.registerWith(registry!!.registrarFor("in.jvapps.system_alert_window"));
        }
        if (!registry!!.hasPlugin("fr.g123k.deviceapps")) {
          DeviceAppsPlugin.registerWith(registry!!.registrarFor("fr.g123k.deviceapps"));
        }
       }

I also register another plugin called **DeviceApps**. This is the DeviceAppsPlugin [DeviceAppsPlugin.java][2]

**Problem**

**In short** 

So the system overlay (which runs in the foreground) calls > the dart callback > invokes a method of the DeviceApps plugin > error occcurs

**Long version**

I have a static callback that is registered [here][3] and it gets called when I have a click interaction with the system alert window. But now I wan't to call the DeviceApps plugin in my dart code from the that static callback

So the method channel will invoke [this][4] and that will run the static callback defined in dart.

This is the static dart callback that is registered and called with a background channel

      static Future<void> systemOverlayOnClickListner(String tag) async {
        switch (tag) {
          case 'button_app_to_foreground':
            DeviceApps.openApp('com.companyname.appname'); // this is where I try to run the plugin
            await SystemAlertWindow.closeSystemWindow();
            break;
        }

The callback will invoke a method of the DeviceApps plugin. And this causes problems because [this][5] method will try to get the package manager from the activity passed in it's constructor. But according to this error the activity is null.

    E/MethodChannel#g123k/device_apps(24210): Failed to handle method call
    E/MethodChannel#g123k/device_apps(24210): java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.pm.PackageManager android.app.Activity.getPackageManager()' on a null object reference
    E/MethodChannel#g123k/device_apps(24210): 	at fr.g123k.deviceapps.DeviceAppsPlugin.openApp(DeviceAppsPlugin.java:141)

So it will invoke the getPackageManager() on a null object. 

The activity is only null when it is being called from this static callback that is called by the background channel.. But not when I call it from the app scope. Why is this the case?

**Conslusion**

So in conclusion calling the plugin works fine when I call it from my app scope. But once the callback is called trough means of the background channel all of the sudden the activity is null.

I cannot just start a isolate in my app and send a message to that from my callback like how its done [here][6]. Because I need this code to work when the app is closed, and a app scoped isolate doesn't run in the background.

So how do I make sure the activity in the DeviceApp.openApp() isn't null? The activity is only being set once, can't it just look at the foreground activity? 

This is the full stack trace

    E/flutter (26735): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'android.content.pm.PackageManager android.app.Activity.getPackageManager()' on a null object reference, null)
    E/flutter (26735): #0      StandardMethodCodec.decodeEnvelope 
    package:flutter/…/services/message_codecs.dart:569
    E/flutter (26735): #1      MethodChannel._invokeMethod 
    package:flutter/…/services/platform_channel.dart:156
    E/flutter (26735): <asynchronous suspension>
    E/flutter (26735): #2      MethodChannel.invokeMethod 
    package:flutter/…/services/platform_channel.dart:329
    E/flutter (26735): #3      DeviceApps.openApp 
    package:device_apps/device_apps.dart:81
    E/flutter (26735): #4      SystemOverlayController.systemOverlayOnClickListner 
    package:appname/…/singletons/system_overlay_controller.dart:51
    E/flutter (26735): #5      callbackDispatcher.<anonymous closure> 
    package:system_alert_window/system_alert_window.dart:136
    E/flutter (26735): #6      MethodChannel._handleAsMethodCall 
    package:flutter/…/services/platform_channel.dart:409
    E/flutter (26735): #7      MethodChannel.setMethodCallHandler.<anonymous closure> 
    package:flutter/…/services/platform_channel.dart:377
    E/flutter (26735): #8      _DefaultBinaryMessenger.handlePlatformMessage 
    package:flutter/…/services/binding.dart:199
    E/flutter (26735): #9      _invoke3.<anonymous closure>  (dart:ui/hooks.dart:290:15)
    E/flutter (26735): #10     _rootRun  (dart:async/zone.dart:1184:13)
    E/flutter (26735): #11     _CustomZone.run  (dart:async/zone.dart:1077:19)
    E/flutter (26735): #12     _CustomZone.runGuarded  (dart:async/zone.dart:979:7)
    E/flutter (26735): #13     _invoke3  (dart:ui/hooks.dart:289:10)
    E/flutter (26735): #14     _dispatchPlatformMessage  (dart:ui/hooks.dart:164:5

**Edit**

I think [this][7] is a similar issue only here they choose to not register the plugin because it is foreground only. Where in my case I want to fork either of these plugins and modify the them so that it also works in the background. How do I do that? 

I am going to try to just add the device apps DeviceApp.openApp()  to the forked system alert window plugin. And use the activity from the system alert way. But obviously this isn't a elegant solution.

  [1]: https://github.com/pvsvamsi/SystemAlertWindow/blob/master/android/src/main/java/in/jvapps/system_alert_window/SystemAlertWindowPlugin.java
  [2]: https://github.com/g123k/flutter_plugin_device_apps/blob/master/android/src/main/java/fr/g123k/deviceapps/DeviceAppsPlugin.java
  [3]: https://github.com/pvsvamsi/SystemAlertWindow/blob/e0b4cd307a08c8b90b0bc1c38ef1c854e374088d/android/src/main/java/in/jvapps/system_alert_window/SystemAlertWindowPlugin.java#L168
  [4]: https://github.com/pvsvamsi/SystemAlertWindow/blob/e0b4cd307a08c8b90b0bc1c38ef1c854e374088d/android/src/main/java/in/jvapps/system_alert_window/SystemAlertWindowPlugin.java#L243
  [5]: https://github.com/g123k/flutter_plugin_device_apps/blob/20d8a64cb5920b0c0a9d067f38b1fc9dc3bafacc/android/src/main/java/fr/g123k/deviceapps/DeviceAppsPlugin.java#L156
  [6]: https://pub.flutter-io.cn/packages/system_alert_window#isolate-communication
  [7]: https://stackoverflow.com/a/58813854/4214922

**Comment by michael-ottink** [comment]
From what I understand you can use the context instead of the activity. Could you replace the activity with the context?

**Comment by g123k** [comment]
The plugin now uses the plugin V2 system + context instead activity, so the problem should be fixed

**Comment by michael-ottink** [comment]
I am still getting the following error using 1.1.0

E/flutter (24866): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method openApp on channel g123k/device_apps)
E/flutter (24866): #0      MethodChannel._invokeMethod 
package:flutter/…/services/platform_channel.dart:154
E/flutter (24866): <asynchronous suspension>
E/flutter (24866): #1      MethodChannel.invokeMethod 
package:flutter/…/services/platform_channel.dart:329
E/flutter (24866): #2      DeviceApps.openApp 
package:device_apps/device_apps.dart:81
E/flutter (24866): #3      SystemOverlayService.systemOverlayOnClickListner 
package:app_name/…/system_overlay/system_overlay_service.dart:42
E/flutter (24866): #4      callbackDispatcher.<anonymous closure> 
package:system_alert_window/system_alert_window.dart:136
E/flutter (24866): #5      MethodChannel._handleAsMethodCall 
package:flutter/…/services/platform_channel.dart:409
E/flutter (24866): #6      MethodChannel.setMethodCallHandler.<anonymous closure> 
package:flutter/…/services/platform_channel.dart:377
E/flutter (24866): #7      _DefaultBinaryMessenger.handlePlatformMessage 
package:flutter/…/services/binding.dart:199
E/flutter (24866): #8      _invoke3.<anonymous closure>  (dart:ui/hooks.dart:290:15)
E/flutter (24866): #9      _rootRun  (dart:async/zone.dart:1184:13)
